---
title: ""
output: 
    pdf_document:
        keep_tex: true
geometry: margin=1in 
fontsize: 12pt
font: Times New Roman
documentclass: article
classoption: letterpaper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

# Schedule of Events 
Provide a three-year calendar or schedule of major collaborative activities, dissemination and publication activities, and any project milestones.


\vspace{10pt}
## Project Milestones 

### Task: Develop the bcGAIM 

\begin{itemize}
    \item 6-8 months: Implement prior(s) for shape-constrained inference for 1$^{\text{st}}$-order and 2$^{\text{nd}}$-order random walks. 
    \item 8-12 months: Implement prior(s) for shape-constrained inference for adaptive smoothing splines. 
    \item 12-16 months: Write paper summarizing these results and submit for publication. 
    \item 12-16 months: Develop an R package so these models (and the approximate inference models) are readily available.
    \item 16-24 months: Implement prior(s) for shape-constrained inference for additional smoothing functions as needed. 
\end{itemize}

### Task: Approximate Inference Algorithm
\begin{itemize}
    \item 8-10 months: Develop, implement, and test approximation algorithms for $\pi( \theta | Y, \alpha )$ and $\pi( \theta | Y, \alpha )$ (for known $\pi(\alpha|Y)$) in Stan when the posterior distribution of $(\eta, \theta, \alpha)$ is not log-concave, when $s$ is a random walk or smoothing spline. 
    \item 10-16 months: Implement the approximate inference algorithm outside of Stan. Compare estimation results to Stan. test 
    \item 14-18 months: Fully characterize the bias introduced by the approximation algorithm through extensive simulation studies. 
    \item 20-24 months: Write a paper summarizing these results and submit for publication. 
    \item 8-10 months: Develop, implement, and test approximation algorithms for estimating the multi-modal posterior distribution $\pi(\alpha|Y)$.
    \item 10-16 months: Implement the approximate inference algorithm outside of Stan. Compare estimation results to Stan.  
    \item 14-18 months: Fully characterize the bias introduced by the approximation algorithm through extensive simulation studies.  
    \item 18-20 months: Apply both approximations to the multi-pollutant models across regions and mortality outcomes.
    \item 20-24 months: Write a paper summarizing these results and submit for publication. 
    \item 20-24 months: Add approximate Bayesian inference models to the R package. 
    \item 24-30 months: Extend the approximation algorithm to hierarchical models (across cities). Compare to the results obtained when fitting the hierarchical model from Stan (exact and approximate inference). 
    \item 30-34 months: Write a paper summarizing these results and submit for publication. 
    \item 30-34 months: Add hierarchical approximate inference model to the R package. 
\end{itemize}


### Task: Multi-Pollutant Application

\begin{itemize}
    \item 12-13 months: Explore performance of bcGAIM in the multi-pollutant model across regions and mortality outcomes.
    \item 13-16 months: Iteratively refine the bcGAIM (including shape-constraining priors) for the multi-pollutant application.
    \item 16-24 months: Extend the multi-pollutant model to a hierarchical model that fits Canada-wide data, using the approximations for $\pi( \theta | Y, \alpha )$ and $\pi( \theta | Y, \alpha )$ if computationally neccesary. 
    \item 24-28 months: Write a paper summarizing these results and submit for publication. 
    \item 24-28 months: Add hierarhical bcGAIM model to the R package.
\end{itemize}


### Task: COVID-19 Application 
\begin{itemize}
    \item 24-26 months: Identify COVID-19 confounders and data sets that may be used to fit a COVID-19 bcGAIM model. 
    \item 26-28 months: Fit the bcGAIM model to COVID-19 mortality data. Use the hierarchical models if data is available. 
    \item 28-32 months: Write a paper summarizing these results and submit for publication. 
\end{itemize}

### External Collaborations

\begin{itemize}
    \item 12-16 months: Identify collaborators and epidemiological studies that may benefit from the applying the bcGAIM.
    \item 16-36 months: Work with collaborations on epidemological studies, as the opportunity arises.
\end{itemize}



\clearpage
\vspace{10pt}
## Dissemination and Publication Activities 

### Year 2 

\begin{itemize}
    \item Submit Paper: Shape-constrained Bayesian inference with interpretable priors.
    \item Submit Paper: Approximate Bayesian inference for non-concave likelihoods (fix $\pi(\alpha|Y)$). 
    \item Submit Paper: Approximate Bayesian inference for $\pi(\alpha|Y)$ and non-concave likelihoods.
    \item Dissemination: Discuss shape-constrained Bayesian inference at 1-2 conferences. 
\end{itemize}

### Year 3 

\begin{itemize}
    \item Submit paper: A multi-pollutant air quality index. 
    \item Submit paper: The effects of multiple pollutant mixtures on COVID-19 mortality.
    \item Submit paper: A hierarchical extension to Approximate Bayesian inference with non-concave likelihoods.
    \item Dissemination: Discuss approximate Bayesian inference for non-concave likelihoods at 1-2 conferences.  
    \item Dissemintation: Discuss the multi-pollutant air quality index at 1-2 conferences.
    \item Dissemintation: Discuss the hierarchical extensions to the multi-pollutant air quality index at 1-2 conferences.
\end{itemize}


\clearpage

## Major Collaborative Activities 

Question: What qualifies as a "major" activity? 

The different components of the bcGAIM project are naturally related, which encourages research collaboration between team members. The bcGAIM is being developed in Stan in the first year, as is the first version of the approximate inference algorithm. Therefore, the bcGAIM model should be written in a way that faciliates incorporating these approximations. Moreover, the approximations should be developed knowing they will be implemented in Stan. In the second year, the two Stan models and the approximate inference algorithm will be extended to a hierarchical formulation. In the multi-pollutant model, the relative risks of time, temperature, and the pollutants are often very small making model hyper-parameters numerically difficult to estimate. Moreover, although the hierahichal structure is at the city-level, nearby cities differ in their distance from each other. Ideally, a hierahichal model should account for how the composition of a mixture of pollutants varies by distance. The numerical difficulties and more complicated hierahichal structure should also encourage strong collaboration at this stage of the project.

The third year is devoted to applications -- applying the fully developed bcGAIM model to the multi-pollutant problem, COVID-19 data, and other epiodemiological applications that arise during the course of the project -- as well as writing papers and producing a useful R package. There is again natural collaboration between those writing and maintaining the R package. The papers will be written independently, but ideally with feedback from the entire research term. They should be in a position to give good feedback as they colloborated on some level throughout the entire project. 

