---
title: "Modeling Linear Combinations of Multiple Pollutants for Health Outcomes"
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
  - \usepackage{fontspec}
  - \usepackage{geometry}
bibliography: CANSSI_Grant.bib
geometry: margin=1in 
fontsize: 12pt
documentclass: article
classoption: letterpaper
link-citations: true
csl: journal-of-the-royal-statistical-society.csl
---

\setmainfont{Calibri}
\vspace{-2em}

# Name and affiliations of lead investigators

Name: Professor Patrick Brown <br/>  
Affiliations: Centre for Global Health Research, St. Michael's Hospital <br/>  
             \hspace*{52.5pt} Department of Statistical Sciences, University of Toronto

Name: Professor Fateh Chebana <br/>  
Affiliation: Institut national de la recherche scientifique 

Name: Professor Cindy Feng <br/>  
Affiliation: School of Epidemiology and Public Health, University of Ottawa



# List of proposed collaborators, titles, and affiliations

Name: Kamal Rai <br/>  
Title: PhD <br/>  
Affiliations: Centre for Global Health Research, St. Michael's Hospital <br/>  
             \hspace*{52.5pt} Department of Statistical Sciences, University of Toronto


Name: Hwashin Shin <br/>  
Title: Adjunct Associate Professor (?) <br/>  
Affiliations: Environmental Health Science and Research Bureau, Health Canada <br/>  
             \hspace*{52.5pt} Department of Mathematics and Statistics, Queen's University 

Name: Céline Campagna <br/>  
Title: PhD <br/>  
Affiliation: Institut National de Santé Publique du Québec


Name: Pierre Masselot <br/>  
Title: Research Fellow <br/>    
Affiliation: London School of Hygiene & Tropical Medicine
   



# List of potential partner organizations (optional)

Centre for Global Health Research, St. Michael's Hospital  <br/>  
Institut National de Santé Publique du Québec <br/>  
Health Canada 


\newpage

# Research Aims

<!-- Limit to 5 pages, including references (include all details). Will be expanded to 7 pages in the full proposal -->

## Introduction 

Possible epidemiological applications include examining the health effects of environmental exposures, such as chemical mixtures, metal mixtures, pesticides, and mixtures of air pollutants [@sanders2015perinatal; @braun2016can; @lazarevic2019statistical; @bobb2015bayesian]. 

The major application considered in this proposal is air pollution. 

## The Model 

We will develop a Bayesian implementation of the *constrained groupwise additive index model* (cGAIM), which we term the bcGAIM. The cGAIM is introduced in @pierre2020aim, but no Bayesian implementation currently exists.
There are differences between the cGAIM and bcGAIM. We begin our discussion of these differences by introducing the cGAIM. For a response distribution $D$, parameter $\theta = (\theta_{1},\ldots,\theta_{d})$, and link function $g$, the cGAIM is,

\vspace{-0.75em}
$$
\begin{aligned}
  Y_{t} | \theta_{t} & \stackrel{i.i.d.}{\sim}  D( \theta_{t} ), \\
  g( \theta ) &= X\beta + 
        \sum\limits_{i=1}^{I} s_{i}(\alpha_{i}^{T} Z_{i} )+ 
        \sum\limits_{k=1}^{K} f_{k}( \eta_{k} ).
\end{aligned}
$$
Here, $Y_{t}$ is the (health) outcome of interest, $X$ is a design matrix, and $\beta$ is a vector of fixed effects. The second sum consists of $K$ smoothing functions $f_{1}, \ldots, f_{K}$ applied to vector-valued confounders $\eta_{k}$. The novelty of the cGAIM lies in its first sum, which fits a smooth function to a linear combination of covariates $Z_{i}$. The cGIAM can enforce a number of hard constraints on the $\alpha_{i}$ or $s_{i}$. For example, it can constrain the entries of $\alpha_{i}$ to be non-negative and sum to one, so that $\alpha_{i}^{T}Z_{i}$ is a weighted sum (*mixture*) of the $Z_{i}$. It can also constrain the shape of the $s_{i}$ by, for example, requiring that $s_{i}$ be monotonic or convex. 

The cGAIM uses an iterative two-step optimization scheme. In the first step, the $\alpha_{i}$ are updated using a quadratic program. In the second step, the $s_{i}$ are updated using the shape-constrained additive model methodology [@pya2015shape]. The bcGAIM will initially be implemented in Stan, a statistical modeling language that performs optimization using Hamiltonian Monte Carlo [@carpenter2017stan]. With Stan performing the optimization, the main task for implementing the bcGAIM in Stan is in developing priors that enforce the constraints seen in the cGAIM. For a simple example of this task, setting a Dirichlet prior on $\alpha_{i}$ constrains it to be a vector of weights [@betancourt2012cruising]. 

Setting priors to enforce shape constraints is much more challenging. In addition to being free of unwanted behavior, the chosen prior should be simple and interpretable so that non-statistical experts can use it. This is difficult to achieve for shape constraints. The first reason for this is that $s_{i}$ may not have any parameters related to the desired constraint; for example, a 1^st^-order random walk has no parameters related to monotonicity. To overcome this, $s_{i}$ could be re-parameterized, the functional form of $s_{i}$ could be exploited, or data augmentation schemes that introduce derivative observations could be used [@riihimaki2010gaussian]. The second reason is that substantial mathemtical analysis is required to ensure priors do not introduce unwanted behavior. For example, a truncated multivariate normal (tMVN) prior can induce monotonicity when placed on the coefficients $\beta^{'}$ of a finite basis expansion of $s_{i}$ [@maatouk2017gaussian]. However, the tMVN prior places neglible mass in near-flat regions of $s_{i}$. While @zhou2020truncated remedy this by introducing a scale parameter to the coordinates of the tMVN distribution, the modified tMVN prior is placed on $\beta^{'}$, not $s_{i}$. In comparison to the tMVN prior, we seek a prior on $s_{i}$ that enforces monotonicity, so that it can be easily explained to non-statistical experts. 
 
**ADD**: Why the bcGAIM - what are its advantages over the cGAIM? Finally, following its implementation in Stan, the bcGAIM will be implemented using non-MCMC inference methods, similar to Iterated Nested Laplace Approximation (INLA) [@rue2009approximate]. These methods provide computational and ease-of-use and benefits, and will expand the types of problems and number of users who can make use of the bcGAIM methodology. 




## Research Questions

In the course of this project, we will use the GAIM to explore the health effects of multiple air pollutants. Recent years have seen increased interest in modeling the joint effect of two or more pollutants in health outcomes [@dominici2010protecting; @billionnet2012estimating; @davalos2017current]. Bayesian approaches can be seen in @blangiardo2019hierarchical, @bobb2013reduced, and @huang2018multivariate. We will consider two research questions in the course of our inquiry, namely,
  
  1. What is the combined effect of multiple pollutants on various daily mortality outcomes?, and
  2. What is the relationship between daily COVID-19 mortality/morbidity and air pollution? 
  
  
### Question 1

The workhorse of the (predominantly frequentist) air pollution literature is the one-pollutant log-linear Poisson regression model. This model accounts for confounders using fixed effects and smooth functions, such as the natural cubic spline [@dominici2002use; @liu2019ambient]. Let the average rate an outcome occurs on day $t$ be denoted by $\lambda_{t}$. Then, a typical one-pollutant model (with pollutant $P_{1,t}$) is, 

\vspace{-0.50em}
$$
\begin{aligned}
  Y_{t} | \lambda_{t} &= \text{Poisson}(\lambda_{t}), \\
  \log(\lambda_{t}) &= X\beta + \gamma_{1} P_{1,t} + \sum\limits_{k=1}^{K} f_{k}(\eta_{k}).
\end{aligned}
$$
Here, $Y_{t}$ is the health outcome of interest, such as respiratory mortality or morbidity. The design matrix $X$ contains day-of-the-week effects and seasonal terms, and the $f_{i}(\eta_{k,*})$ are smooth functions of potential confounders such as time and temperature. One extension of this model would fit $P_{1,t}$ to a smooth function $s_{1}$. More generally, we could fit $N$ pollutants to $N$ smooth functions, $s_{1}, \ldots, s_{N}$. A third alternative, which we propose here, is to model $N$ pollutants using the GAIM. 

Air pollution is an excellent application area for the bcGAIM. People are exposed to the mixture of pollutants in their environment, many of which are highly correlated [@guowen2020multi]. Thus, health effects the single pollutant model attributes to $P_{1}$ may very well be caused by a correlated pollutant, or only be present within certain combinations of a mixture of pollutants. Indeed, @franklin2008impact found that the effect of ozone on non-accidental mortality was "substantially reduced" after adjusting for particle sulfate. In @liu2019ambient, the authors found significant differences in the percentage change in all-cause mortality attributable to PM~2.5~ and PM~10~ when adjusting for NO~2~ or SO~2~.

Like the cGAIM, the bcGAIM is a flexible and extensible statistical model. The researcher can choose the number $I$ of smooth functions $s_{i}$ and the number of covariates $n_{i}$ in each $s_{i}$. For example, an air pollution model could have one smooth function $s_{1}$ and two covariates $\gamma_{1,t}$ and $\gamma_{2,t}$, where $\gamma_{1,t}$ is the time-varying concentration of ozone (O~3~) and $\gamma_{2,t}$ is the time-varying concentration of particulate matter smaller than 2.5 $\mu$g (PM~2.5~). In this case, the weights $\alpha = (\alpha_{1}, \alpha_{2})$ give the relative contribution of O~3~ and PM~2.5~ to the health outcome of interest. Alternatively, the model could have 3 additional pollutants -- nitrogen dioxide (NO~2~), sulfur dioxide (SO~2~), and particulate matter smaller than 10 $\mu$g (PM~10~) -- such that the 5 weights give the relative contribution of each pollutant. The model could also include interaction terms, or additional smooth functions $s_{i}$ that group (for example) correlated pollutants.

It is therefore crucial to extend the one-pollutant model in a way that attributes health effects to the correct mixture of pollutants, suggesting that the model should conduct inference on mixtures. As for extending the $s_{i}$ to be non-linear, there is evidence that some health outcomes are nonlinearly related to pollution levels, and that synergistic effects occur when multiple pollutants are present at higher levels [@feng2016impact; @xia2006cumulative]. These extensions make the GAIM especially well-suited to estimating nonlinear effects of (pollutant) mixtures: the smooth function(s) $s_{i}$ estimate the effects of their respective weighted sums, where the weights give the relative contribution of the components.

The multiple pollutant problem has received increased intention in recent years. Five approaches are detailed in @davalos2017current. Of these 5 methods, they note that adding additive main effects can lead to biased estimates in the presence of highly correlated variables, and that nonparameteric methods are often not very interpretable. The research teams and stakeholders involved in air pollution research are often diverse and inter-disciplinary. This makes it crucial that models have interpretable parameters, so that estimation results can be easily communicated to non-specialists. While the unsupervised dimension reduction methods (such as principle components analysis and clustering) identified in @davalos2017current are difficult to interpret, they note some supervised methods that consider weighted sums of pollutant concentrations. For example,  @pachon2012development specify weights from data rather than estimating them, while @roberts2006investigating introduces a model that is equivalent to assuming that $s_{1}$ is linear. While these are viable statistical methods, they are not as flexible or extensible as the GAIM.

@davalos2017current also discusses non-parametric methods, including Bayesian Kernel Machine Regression (BKMR). BKMR allows for estimation and variable selection. It was introduced in @bobb2015bayesian, and an R package was released with @bobb2018statistical. BKMR models an exposure-response surface -- the exposures can be pollutants and the response nonaccidental mortality -- via a kernel function. Using a hierarchical Bayesian variable selection method, BKMR can select one pollutant from a group of correlated ones, and is interpreted by visualizing cross-sections of a potentially high-dimensional exposure-response surface. Unlike the GAIM, it does not have easily interpretable parameters. This makes the GAIM more suitable to the communication demands of inter-disciplinary research areas such as air pollution.

While there has been significant research interest in the multiple pollutant problem, the models proposed to date have either computational limitations or limited interpretability. In contrast, the GAIM has interpretable parameters and its computational burden does not scale with the dimensionality of its inputs. Therefore, using the GAIM to examine the health effect of a mixture of pollutants will provide interpretable and communicable results on this research question. Finally, note that while air pollution is the main example in this proposal, the GAIM has applications wherever the target of inference is a mixture of covariates that relate nonlinearly to an outcome of interest. 


### Question 2

The relationship between daily COVID-19 deaths and air pollution levels has become an active area of research in recent months. For instance, @wu2020exposure apply a zero-inflated negative bionomial model U.S. data, where the zero-inflation accounts for U.S. counties with no COVID-19 deaths. They use a log-linear link function with a state-level random effect, and find that a 1 $\mu$g increase in long-term exposure to ambient PM~2.5~ increases the COVID-19 death rate by 15%. Additional studies that examine this relationship include @conticini2020can, @sciomer2020sars, and @setti2020searching. 

However, much work remains to be done. For instance, non-COVID-19 daily mortality data is generally not yet available, such that we do not have an accurate measure of excess deaths attributable to COVID-19, especially among vulnerable populations such as seniors. These excess deaths could be attributable to under-reported COVID-19 case and death counts (due to limited testing), restricted access to care for patients with other health conditions, or potential reporting delays. Moreover, cumulative COVID-19 mortality will likely continue to rise for some time, making the question of excess deaths due to COVID-19 best suited to an ongoing inquiry that may help inform subsequent public health responses.

We will use the GAIM to examine the relationship between COVID-19 deaths and long-term exposure to air pollution. Compared to the log-linear negative binomial model in @wu2020exposure, the GAIM is scaleable, interpretable, and can capture non-linearities in the relationship between mixtures and the response. To apply the GAIM to this research question, we must choose the outcome of interest $Y_{t}$ as COVID-19 deaths. To specifically investigate seniors, we may (for example) take $Y_{t}$ to be those aged 65+. Applying the GAIM to air pollution and COVID-19 death data will allow us to ascertain which mixtures of pollutants increase COVID-19 mortality, as well as how their effects differ among age groups. 

This inquiry will make two contributions to the growing COVID-19 literature. The first is that it will help determine how different mixtures of air pollutants amplify the impact of COVID-19. The second is that since people in different regions are exposed to different mixtures of pollutants, it will help identify which mixtures of pollutants have the largest impact on COVID-19 deaths. Both contributions will also further our understanding of the health impacts of air pollution.


## References 
<!-- Source: https://stackoverflow.com/questions/46738721/how-can-i-bring-back-indentation-workaround-in-rmarkdown-pandoc-genuine-referenc -->
\setlength{\parskip}{1pt}
<div id="refs"></div>
\setlength{\parskip}{8pt}



\newpage 
# Anticipated roles of trainees (students and post-doctoral fellows)

<!-- Limit to 1/2 page. Full details will be included in the full proposal --> 

Kamal will develop the Bayesian implementation of the GAIM models in Stan. This includes exploring determining appropriate prior distributions for the weights $\alpha$, developing visualizations that communicate modeling results, and assisting other project members in developing shape constraints. He will be responsible for producing paper(s) summarizing the results of this model when run on Canadian air pollution and mortality data. To facilitate team communication and cohesion, he will also split time between Toronto (at the Centre for Global Health Research) and Ottawa (at the University of Ottawa), and use the proximity of the University of Ottawa to Quebec to occasionally visit project collaborators located there.

The University of Toronto PhD student will develop non-MCMC methods to conduct inference on the GAIM, and compare its results from those obtained from the Stan implementation. The University of Laval/University of Ottawa PhD student will develop methods to conduct shape-constrained (Bayesian) inference, and examine the relationship between COVID-19 deaths and air pollution levels. 


<!-- 
### Anticipated organization of collaborations

Not necessary in the LOI. This will be included in the full proposal. 
--> 

# Plans for dissemination and communication

<!-- Limit to 5 sentences. This will be expanded in a full proposal. -->

The lead investigators of this proposal have a track record of publishing research results in leading statistical and epidemiological journals, and aim to publish the results of this project in high-impact journals. The results and findings of this multiple pollutant inquiry will also be shared with Health Canada and the Institut National de Santé Publique du Québec. 


# Suggested reviewers

Any suggestions? 

# Five CVs

<!-- Degrees, current position(s), selected peer-reviewed publications (last 6 years), other evidence of impact and contributions (last 6 years), and numbers of undergraduate, master’s level, PhD level and postdoctoral trainees (last 6 years). --> 

  - Patrick, Fateh, Hwashin, Meredith (?), Cindy  


# Preliminary budget description

<!-- Limit to 1/4 of a page. This will be expanded in a full proposal. --> 

The CANSSI Collaborative Research Team (CRT) grant is for $180,000 over 3 years. We propose the budget:

  1. $30,000/year to support post-doctoral funding.
  2. $12,000/year to support a Laval University or University of Ottawa PhD student.
  3. $12,000/year to support a University of Toronto PhD student.
  4. $6,000/year to support travel to/from the cities of the lead investigators -- Toronto, Ottawa, and Quebec -- and annual team meetings held around the Statistical Society of Canada conference.
